services:
  step-daddy-live-hd:
    network_mode: "service:gluetun"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
        API_URL: ${API_URL}
        PROXY_CONTENT: ${PROXY_CONTENT}
        SOCKS5: ${SOCKS5}
    environment:
      - PORT=${PORT}
      - API_URL=${API_URL}
      - PROXY_CONTENT=${PROXY_CONTENT}
      - SOCKS5=${SOCKS5}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PROTON_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped
